name: sign.yml

on:
  workflow_dispatch:
  schedule:
    - cron: '50 15 * * *'  # 每天24:00执行一次
jobs:
  build:
    name: 流程签到
    runs-on: ubuntu-latest
    env:
      SXMD_ACCOUNT: ${{ secrets.SXMD_ACCOUNT }}
      SXMD_PASSWORD: ${{ secrets.SXMD_PASSWORD }}
      YSQ_ACCOUNT: ${{ secrets.YSQ_ACCOUNT }}
      YSQ_PASSWORD: ${{ secrets.YSQ_PASSWORD }}
    steps:
        - name: 检查
          uses: actions/checkout@v4

        - name: 设置python环境
          uses: actions/setup-python@v5
          with:
            python-version: "3.x"

        - name: 安装依赖
          run: |
              python -m pip install --upgrade pip
              pip install -r ./config/requirements.txt
        - name: 运行书香门第签到脚本
          run: |
              python ./python/sxmd.py
        - name: 运行源社区签到脚本
          run: |
              python ./python/ysq.py
        - name: 删除该流程多余仅保留五条记录
          shell: bash
          run: |
                    current_run_id=$(echo "$GITHUB_RUN_ID")
                    runs=$(curl -s -X GET "https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}/runs" \
                      -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Accept: application/vnd.github.v3+json" | jq -r '.workflow_runs[].id')
                    echo "$runs"
                        keep_runs=$(echo "$runs" | head -n 5)
                        for run_id in $runs; do
                          if [ "$run_id" != "$current_run_id" ] && [[ ! "$keep_runs" =~ "$run_id" ]]; then
                            curl -s -X DELETE "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id" \
                              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                              -H "Accept: application/vnd.github.v3+json" > /dev/null
                          fi
                        done  