name: sign.yml

on:
  workflow_dispatch:
  schedule:
    - cron: '50 15 * * *'  # 每天24:00执行一次
jobs:
  build:
    name: 流程签到
    runs-on: ubuntu-latest
    env:
      SXMD_ACCOUNT: ${{ secrets.SXMD_ACCOUNT }}
      SXMD_PASSWORD: ${{ secrets.SXMD_PASSWORD }}
      YSQ_ACCOUNT: ${{ secrets.YSQ_ACCOUNT }}
      YSQ_PASSWORD: ${{ secrets.YSQ_PASSWORD }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      AIM_EMAIL: ${{ secrets.AIM_EMAIL }}
    steps:
        - name: 检查
          uses: actions/checkout@v4

        - name: 设置python环境
          uses: actions/setup-python@v5
          with:
            python-version: "3.x"

        - name: 安装依赖
          run: |
              python -m pip install --upgrade pip
              pip install -r ./config/requirements.txt
        - name: 运行书香门第签到脚本
          if: env.SXMD_ACCOUNT != '' && env.SXMD_PASSWORD != ''
          run: |
               tt=$(python ./python/sxmd.py)
               echo "sxmdinfo=$tt" >> "$GITHUB_ENV"
               echo "version=$(date +'%Y-%m-%d %H:%M:%S')" >>$GITHUB_ENV
        - name: 运行源社区签到脚本
          if: env.YSQ_ACCOUNT != '' && env.YSQ_PASSWORD != ''
          run: |
              yy=$(python ./python/ysq.py)
              echo "ysqinfo=$yy" >> "$GITHUB_ENV"
              
        - name: 删除该流程多余仅保留五条记录
          shell: bash
          run: |
                    current_run_id=$(echo "$GITHUB_RUN_ID")
                    runs=$(curl -s -X GET "https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}/runs" \
                      -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Accept: application/vnd.github.v3+json" | jq -r '.workflow_runs[].id')
                    echo "$runs"
                        keep_runs=$(echo "$runs" | head -n 5)
                        for run_id in $runs; do
                          if [ "$run_id" != "$current_run_id" ] && [[ ! "$keep_runs" =~ "$run_id" ]]; then
                            curl -s -X DELETE "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id" \
                              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                              -H "Accept: application/vnd.github.v3+json" > /dev/null
                          fi
                        done  

        - name: Send email
          uses: bgvioletsky/send_email@v1.0.0  # 替换为你的仓库信息
          if: env.EMAIL_USERNAME != '' && env.EMAIL_PASSWORD != ''
          with:
            server_address: smtp.163.com
            server_port: 465
            username: ${{ env.EMAIL_USERNAME }}
            password: ${{ env.EMAIL_PASSWORD }}
            subject: 自动签到
            body: |
              签到结果：
                书香门第： ${{env.sxmdinfo}}
                源社区：${{env.ysqinfo}}
                签到时间：${{ env.version }}
            to: ${{ env.AIM_EMAIL }}
            from: ${{ env.EMAIL_USERNAME }}
            html: false
                